server.port: 8888

spring.cloud.config.server:
  git:
    uri: https://gitlab.com/analytic-workbench/Implementation/analytic-workbench-configuration-default.git
    search-paths: "analytic-workbench-configuration-default/configuration/{application}"
    cloneOnStart: true
    force-pull: true
    username: scipionyx
    password: soeusei11
    default-label: master 
    timeout: 100
    repos:
      non-production:
        pattern:
        - "*/*dev*"
        - "*/*test*"
        uri: https://gitlab.com/analytic-workbench/Implementation/analytic-workbench-configuration-development.git
        search-paths: "analytic-workbench-configuration-development/configuration/{application}"
        cloneOnStart: true
        force-pull: true
        timeout: 100
        username: scipionyx
        password: soeusei11
      production:
        pattern:
        - "*/*prod*"
        - "*/*uat*"
        uri: https://gitlab.com/analytic-workbench/Implementation/analytic-workbench-configuration-production.git
        search-paths: "analytic-workbench-configuration-production/configuration/{application}"
        cloneOnStart: true
        force-pull: true
        timeout: 100
        username: scipionyx
        password: soeusei11

management.security:
  enabled: false
  role: SUPERUSER      

security.user:
  name: secret
  password: secret